import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dashboard-home',
  templateUrl: './dashboard-home.component.html',
  styleUrls: ['./dashboard-home.component.scss']
})
export class DashboardHomeComponent implements OnInit {
  userName = '';
  greeting = '';
  dailyQuote = '';
  mood: string | null = null;
  todayDate = '';
  efemeride = '';

  private quotes: string[] = [
    '“Cuidar de ti misma no es egoísmo. Es amor propio.”',
    '“Lo que no expresas con palabras, déjalo salir con acciones.”',
    '“Respira hondo, suelta y sigue.”',
    '“La serenidad comienza con un solo paso.”',
    '“Eres más fuerte de lo que crees.”',
    '“Cada logro comienza con la decisión de intentarlo.”',
    '“Acepta lo que es, deja ir lo que fue y ten fe en lo que será.”',
    '“La gratitud convierte lo que tenemos en suficiente.”',
    '“Tu única competencia eres tú mismo.”',
    '“Los pequeños pasos también te llevan a la meta.”',
    '“La calma empieza con una respiración profunda.”',
    '“Permítete descansar para poder brillar.”',
    '“Hoy es un buen día para reír sin motivo.”',
    '“El amor propio es el inicio de una vida plena.”',
    '“Transforma tus pensamientos y cambiarás tu mundo.”',
    '“Agradece las pequeñas victorias de cada día.”',
    '“Atrévete a ser tú en un mundo que intenta que seas otro.”',
    '“La felicidad se encuentra en el presente.”',
    '“Eres la obra más hermosa que trabajarás jamás.”',
    '“El miedo es solo una señal de que estás creciendo.”',
    '“Confía en tus capacidades y vencerás tus dudas.”',
    '“El silencio interior es donde encuentras tu fuerza.”',
    '“Cuida tus pensamientos; se convierten en tus palabras.”',
    '“Permítete sentir para poder sanar.”',
    '“La valentía no es no sentir miedo, sino avanzar a pesar de él.”',
    '“Tú decides el rumbo de tu vida.”',
    '“La verdadera belleza es la autenticidad.”',
    '“Sé amable contigo como lo eres con los demás.”',
    '“Cultiva la paciencia, la paz llegará.”',
    '“Tu mente es un jardín, cultiva pensamientos positivos.”',
    '“El cambio comienza cuando te das permiso para ser tú mismo.”',
    '“Cada día es una nueva oportunidad para empezar.”',
    '“Permítete soltar lo que ya no sirve.”',
    '“El presente es todo lo que necesitas.”',
    '“Encuentra paz en la sencillez.”',
    '“La gratitud es la memoria del corazón.”',
    '“Abre tu mente, abraza la posibilidad.”',
    '“Siembra amor y recolectarás felicidad.”',
    '“El tiempo que te dedicas es tu mejor inversión.”',
    '“Eres suficiente tal como eres.”',
    '“La serenidad se halla en la aceptación.”',
    '“Un paso a la vez es progreso.”',
    '“Permite que tu luz interior brille.”',
    '“La resiliencia nace de las caídas.”',
    '“El perdón libera el alma.”',
    '“El autocuidado no es lujo, es prioridad.”',
    '“Tu voz interior es tu guía más fiel.”',
    '“La armonía comienza desde adentro.”',
    '“Abraza la imperfección como parte de tu belleza.”',
    '“Escucha tu corazón, sabe caminos.”',
    '“El optimismo es un acto de valentía.”',
    '“Tienes todo lo que necesitas en tu interior.”',
    '“Deja que la gratitud te eleve.”',
    '“Cree en tus sueños y ellos creerán en ti.”',
    '“La confianza se construye con cada paso.”',
    '“Cada experiencia te hace más sabio.”',
    '“Tu historia importa.”',
    '“La paz interior es tu mejor refugio.”',
    '“Sé gentil con tu proceso.”',
    '“Ama cada versión de ti.”',
    '“Cada respiro es un regalo.”',
    '“La fortaleza nace de la vulnerabilidad.”',
    '“Eres capaz de grandes cosas.”',
    '“La intención clara guía tu camino.”',
    '“Encuentra belleza en la quietud.”',
    '“El cambio es la única constante.”',
    '“Tu mente es poderosa, úsala sabiamente.”',
    '“Lo mejor está por venir.”',
    '“La gratitud engrandece el alma.”',
    '“Cuida tu paz por encima de todo.”',
    '“Sonríe, la vida es ahora.”',
    '“Abre tu mente a nuevas perspectivas.”',
    '“La claridad llega con la calma.”',
    '“Agradece el aquí y el ahora.”',
    '“Eres el autor de tu destino.”',
    '“Permítete brillar sin miedo.”',
    '“La paciencia cultiva la esperanza.”',
    '“La serenidad es la clave del bienestar.”',
    '“Vive con propósito y pasión.”',
    '“La gratitud es la llave de la felicidad.”',
    '“Encuentra confort en la simplicidad.”',
    '“Aprecia tu propio crecimiento.”',
    '“Eres un ser en constante transformación.”',
    '“Cultiva pensamientos de amor.”',
    '“Confía en el proceso de la vida.”',
    '“La mente en calma resuelve con claridad.”',
    '“Acepta tus emociones sin juzgarte.”',
    '“El amor propio es tu mayor aliado.”',
    '“Cada día trae una nueva posibilidad.”',
    '“Vive con gratitud y serás feliz.”',
    '“La fuerza está en tu interior.”',
    '“Permite que tus sueños te guíen.”',
    '“Encuentra la belleza en tus cicatrices.”',
    '“Cultiva la esperanza cada día.”',
    '“La armonía interior irradia paz.”',
    '“Sé luz en tu propio camino.”',
    '“Negociar contigo mismo es aceptar tus límites.”',
    '“La reflexión abre puertas.”',
    '“Conecta con tu esencia.”',
    '“Eres digno de amor y respeto.”',
    '“La gratitud transforma el dolor en aprendizaje.”',
    '“Permítete soltar el pasado.”',
    '“La plenitud nace de la aceptación.”',
    '“Tu intuición sabe la verdad.”',
    '“Escucha el susurro de tu alma.”',
    '“La amabilidad contigo mismo es sanadora.”',
    '“Cree en tu capacidad de sanar.”',
    '“La resiliencia florece en el corazón.”',
    '“Cada paso consciente es un triunfo.”',
    '“Permítete pausar y recargar.”',
    '“Tu mente es tu hogar, mantenla en paz.”',
    '“La gratitud despierta alegría.”',
    '“Vive con autenticidad.”',
    '“La serenidad es un estado de mente.”',
    '“Encuentra armonía en la rutina.”',
    '“Eres la paz que buscas.”',
    '“Acepta cada etapa de tu vida.”',
    '“La fuerza emerge de la adversidad.”',
    '“Los sueños comienzan con un pensamiento.”',
    '“El amor propio atrae bienestar.”',
    '“Confía en tus pasos.”',
    '“La gratitud guía el alma.”',
    '“Vive con presencia.”',
    '“La calma interior ilumina el camino.”',
    '“Permítete sentir el momento.”',
    '“Tu corazón conoce el camino.”',
    '“Eres suficiente en cada momento.”',
    '“La esperanza renace cada amanecer.”',
    '“Cultiva la paz todos los días.”',
    '“La gratitud es un acto revolucionario.”',
    '“Brilla con tu luz única.”',
    '“En el silencio encuentras la respuesta.”',
    '“La aceptación es liberadora.”',
    '“Ama tu proceso de crecimiento.”',
    '“La serenidad reside en la mente.”',
    '“Permítete ser feliz ahora.”',
    '“Eres un universo en expansión.”',
    '“La gratitud abre el corazón.”',
    '“Encuentra belleza en lo cotidiano.”',
    '“Tu determinación define tu camino.”',
    '“La calma es tu mejor consejera.”',
    '“Permítete renacer cada día.”',
    '“La gratitud es fuerza.”',
    '“Eres la obra maestra en creación.”',
    '“La paz interior es poderosa.”',
    '“El amor propio sana.”',
    '“Cultiva sueños con intención.”',
    '“La serenidad inicia con aceptación.”',
    '“Permítete vivir en equilibrio.”'
  ];

// ... existing code ...
private efemerides: { [key: string]: string } = {
  '4/1': 'Día Mundial del Braille (A/RES/73/161)',
  '24/1': 'Día Internacional de la Educación (A/RES/73/25) y Día Mundial de la Cultura Africana y de los Afrodescendientes (UNESCO)',
  '26/1': 'Día Internacional de la Energía Limpia (A/RES/77/327)',
  '27/1': 'Día Internacional de Conmemoración anual en memoria de las víctimas del Holocausto (A/RES/60/7)',
  '28/1': 'Día Internacional de la Coexistencia Pacífica (A/RES/79/269)',
  '1/2': 'Semana Mundial de la Armonía Interconfesional (A/RES/65/5)',
  '2/2': 'Día Mundial de los Humedales (A/RES/75/317)',
  '4/2': 'Día Internacional de la Fraternidad Humana (A/RES/75/200)',
  '6/2': 'Día Internacional de Tolerancia Cero con la Mutilación Genital Femenina (A/RES/67/146)',
  '10/2': 'Día Mundial de las Legumbres (A/RES/73/251)',
  '11/2': 'Día Internacional de la Mujer y la Niña en la Ciencia (A/RES/70/212)',
  '12/2': 'Día Internacional para la Prevención del Extremismo Violento cuando Conduzca al Terrorismo (A/RES/77/243)',
  '13/2': 'Día Mundial de la Radio (A/RES/67/124)',
  '17/2': 'Día Mundial de la Resiliencia del Turismo (A/RES/77/269)',
  '20/2': 'Día Mundial de la Justicia Social (A/RES/62/10)',
  '21/2': 'Día Internacional de la Lengua Materna (A/RES/56/262)',
  '1/3': 'Día de la Cero Discriminación (ONUSIDA)',
  '3/3': 'Día Mundial de la Vida Silvestre (A/RES/68/205)',
  '5/3': 'Día Internacional para Concienciar sobre el Desarme y la No Proliferación (A/RES/77/51)',
  '8/3': 'Día Internacional de la Mujer',
  '10/3': 'Día Internacional de las Juezas (A/RES/75/274)',
  '15/3': 'Día Internacional para Combatir la Islamofobia (A/RES/76/254)',
  '20/3': 'Día Internacional de la Felicidad (A/RES/66/281)',
  '21/3': 'Día Internacional de la Eliminación de la Discriminación Racial (A/RES/2142 (XXI)), Día Mundial del Síndrome de Down (A/RES/66/149)',
  '22/3': 'Día Mundial del Agua (A/RES/47/193)',
  '23/3': 'Día Meteorológico Mundial (OMM) (WMO/EC-XII/Res.6)',
  '24/3': 'Día Internacional del Derecho a la Verdad en relación con Violaciones Graves de los Derechos Humanos y de la Dignidad de las Víctimas (A/RES/65/196)',
  '25/3': 'Día internacional de Solidaridad con los miembros del personal detenidos o desaparecidos (A/RES/49/59) yDía Internacional de Recuerdo de las Víctimas de la Esclavitud y la Trata Transatlántica de Esclavos (A/RES/62/122)',
  '30/3': 'Día Internacional de Cero Desechos (A/RES/77/161)',
  '2/4': 'Día Mundial de Concienciación sobre el Autismo (A/RES/62/139)',
  '4/4': 'Día Internacional de información sobre el peligro de las minas y de asistencia para las actividades relativas a las minas (A/RES/60/97)',
  '5/4': 'Día Internacional de la Conciencia (A/RES/73/329)',
  '6/4': 'Día Internacional del Deporte para el Desarrollo y la Paz (A/RES/67/296)',
  '7/4': 'Día Mundial de la Salud (OMS) (A/RES/58/234) y Día Internacional de Reflexión sobre el Genocidio de 1994 contra los Tutsis en Rwanda (WHA/A.2/Res.35)',
  '12/4': 'Día Internacional de los Vuelos Espaciales Tripulados (A/RES/65/271)',
  '14/4': 'Día Mundial de la enfermedad de Chagas',
  '19/4': 'Día de la lengua china',
  '21/4': 'Día Mundial de la Creatividad y la Innovación (A/RES/71/284)',
  '22/4': 'Día Internacional de la Madre Tierra (A/RES/63/278)',
  '23/4': 'Día del Idioma Español en las Naciones Unidas y Día Mundial del Libro y del Derecho de Autor (UNESCO 28 C/Resolution 3.18)',
  '24/4': 'Día Internacional de las Niñas en las TIC (ITU) (se celebrará el 24 de abril en 2025) y Día de la lengua inglesa',
  '25/4': 'Día Mundial del Paludismo (OMS)',
  '26/4': 'Día Mundial de la Propiedad Intelectual (OMPI) y Día Internacional de Recordatorio del Desastre de Chernóbyl (A/RES/71/125)',
  '28/4': 'Día Mundial de la Seguridad y Salud en el Trabajo',
  '30/4': 'Día Internacional del Jazz (UNESCO 36 C/Resolution 39)',
  '2/5': 'Día Mundial del Atún (A/RES/71/124)',
  '3/5': 'Día Mundial de la Libertad de Prensa (UNESCO 26 C/Resolution 4.3)',
  '5/5': 'Día Mundial de la Lengua Portuguesa',
  '10/5': 'Día Mundial de las Aves Migratorias (PNUMA)',
  '11/5': 'Día Mundial de las Aves Migratorias (PNUMA)',
  '12/5': 'Día Internacional de la Sanidad Vegetal (A/RES/76/256)',
  '15/5': 'Día Internacional de las Familias (A/RES/47/237)',
  '16/5': 'Día Internacional de la Luz (UNESCO) (UNESCO 39 C/Resolution 16) y Día Internacional de la Convivencia en Paz (A/RES/72/130) ',
  '17/5': 'Día Mundial de las Telecomunicaciones y la Sociedad de la Información (A/RES/60/252)',
  '19/5': 'Día Mundial del Juego Limpio (A/RES/78/310)',
  '20/5': 'Día Mundial de las Abejas (A/RES/72/211)',
  '21/5': 'Día Mundial de la Diversidad Cultural para el Diálogo y el Desarrollo (A/RES/57/249)',
  '22/5': 'Día Internacional de la Diversidad Biológica (A/RES/55/201)',
  '23/5': 'Día Internacional para la Erradicación de la Fístula Obstétrica (A/RES/67/147)',
  '25/5': 'Semana de Solidaridad con los pueblos de los territorios no autónomos (A/RES/54/91)',
  '29/5': 'Día Internacional del Personal de Paz de las Naciones Unidas (A/RES/57/129)',
  '30/5': 'Día Internacional de la Papa (A/RES/78/123)',
  '31/5': 'Día Mundial Sin Tabaco (OMS) (WHA Resolution 42.19)',
  '1/6': 'Día Mundial de las Madres y los Padres (A/RES/66/292)',
  '3/6': 'Día Mundial de la Bicicleta (A/RES/72/272)',
  '4/6': 'Día Internacional de los Niños Víctimas Inocentes de Agresión (A/RES/ES-7/8)',
  '5/6': 'Día Mundial del Medio Ambiente (A/RES/2994 (XXVII)) y Día Internacional de la Lucha contra la Pesca Ilegal, No Declarada y No Reglamentada (A/RES/72/72)',
  '6/6': 'Día de la lengua rusa',
  '7/6': 'Día Mundial de la Inocuidad de los Alimentos (A/RES/73/250)',
  '8/6': 'Día Mundial de los Océanos (A/RES/63/111)',
  '10/6': 'Día Internacional para el Diálogo entre Civilizaciones (A/RES/78/286)',
  '11/6': 'Día Internacional del Juego (A/78/L.53)',
  '12/6': 'Día Mundial contra el Trabajo Infantil',
  '13/6': 'Día Internacional de Sensibilización sobre el Albinismo (A/RES/69/170)',
  '14/6': 'Día Mundial del Donante de Sangre (OMS) (WHA Resolution 58.13)',
  '15/6': 'Día Mundial de Toma de Conciencia de Abuso y Maltrato en la Vejez (A/RES/66/127)',
  '16/6': 'Día Internacional de las Remesas Familiares (A/RES/72/281)',
  '17/6': 'Día Mundial de Lucha contra la Desertificación (A/RES/49/115)',
  '18/6': 'Día Internacional para Contrarrestar el Discurso de Odio (A/RES/75/309) y Día de la Gastronomía Sostenible (A/RES/71/246)',
  '19/6': 'Día Internacional para la Eliminación de la Violencia Sexual en los Conflictos (A/RES/69/293)',
  '20/6': 'Día Mundial de los Refugiados (A/RES/55/76)',
  '21/6': 'Día Internacional de la Celebración del Solsticio (A/RES/73/300) y Día Internacional del Yoga (A/RES/69/131)',
  '23/6': 'Día de las Naciones Unidas para la Administración Pública (A/RES/57/277) y Día Internacional de las Viudas (A/RES/65/189)',
  '24/6': 'Día Internacional de las Mujeres en la Diplomacia (A/RES/76/269)',
  '25/6': 'Día de la Gente de Mar (OIM) (STCW/CONF.2/DC/4 en inglés)',
  '26/6': 'Día Internacional en Apoyo de las Víctimas de la Tortura (A/RES/52/149) y Día Internacional de la Lucha contra el Uso Indebido y el Tráfico Ilícito de Drogas (A/RES/42/112)',
  '27/6': 'Día de las Microempresas y las Pequeñas y Medianas Empresa (A/RES/71/279)',
  '29/6': 'Día Internacional de los Trópicos (A/RES/71/279)',
  '30/6': 'Día Internacional de los Asteroides (A/RES/71/90) y Día Internacional del Parlamentarismo (A/RES/72/278)',
  '6/7': 'Día Internacional de las Cooperativas (A/RES/47/90)',
  '7/7': 'Día Mundial de la Lengua Kiswahili (A/RES/78/312)',
  '11/7': 'Día Internacional de Reflexión y Conmemoración del Genocidio de Srebrenica de 1995 (A/RES/78/282) y Día Mundial de la Población (A/RES/45/216)',
  '12/7': 'Día Internacional de la Lucha contra las Tormentas de Arena y Polvo (A/RES/77/294) y Día Internacional de la Esperanza (A/RES/79/270)',
  '15/7': 'Día Mundial de las Habilidades de la Juventud (A/RES/69/145)',
  '18/7': 'Día Internacional de Nelson Mandela (A/RES/64/13)',
  '20/7': 'Día Internacional de la Luna (Borrador A/RES/76/415) y Día Mundial del Ajedrez (A/RES/74/22)',
  '25/7': 'Día Internacional para el Bienestar Judicial (A/RES/79/266), Día Internacional de las Mujeres y Niñas Afrodescendientes (A/RES/78/323), y Día Mundial para la Prevención de los Ahogamientos (A/RES/75/273)',
  '28/7': 'Día Mundial contra la Hepatitis (OMS)',
  '30/7': 'Día Internacional de la Amistad (A/RES/65/275) y Día Mundial contra la Trata (A/RES/68/192)',
  '1/8': 'Semana Mundial de la Lactancia Materna',
  '9/8': 'Día Internacional de los Pueblos Indígenas (A/RES/49/214)',
  '11/8': 'Día Mundial de los Tambores Metálicos (A/RES/77/316)',
  '12/8': 'Día Internacional de la Juventud (A/RES/54/120)',
  '19/8': 'Día Mundial de la Asistencia Humanitaria (A/RES/63/139)',
  '21/8': 'Día Internacional de Conmemoración y Homenaje a las Víctimas del Terrorismo (A/RES/72/165)',
  '22/8': 'Día de Conmemoración de las Víctimas de Actos de Violencia basados en la Religión o las Creencias (A/RES/73/296)',
  '23/8': 'Día Internacional del Recuerdo de la Trata de Esclavos y de su Abolición (UNESCO 29 C/Resolution 40)',
  '27/8': 'Día Mundial de los Lagos (A/RES/79/142)',
  '29/8': 'Día Internacional contra los Ensayos Nucleares (A/RES/64/35)',
  '30/8': 'Día Internacional de las Víctimas de Desapariciones Forzadas (A/RES/65/209)',
  '31/8': 'Día Internacional de los Afrodescendientes (A/RES/75/170)',
  '5/9': 'Día Internacional de la Beneficencia (A/RES/67/105)',
  '7/9': 'Día Mundial de Concienciación sobre la Distrofia de Duchenne (A/RES/78/12), Día Internacional de la Cooperación Policial (A/RES/77/241), y Día Internacional del Aire Limpio por un Cielo Azul (A/RES/74/212)',
  '8/9': 'Día Internacional de la Alfabetización (UNESCO 14 C/Resolution 1.441)',
  '9/9': 'Día Internacional para Proteger la Educación de Ataques (A/RES/74/275)',
  '12/9': 'Día de las Naciones Unidas para la Cooperación Sur-Sur (A/RES/58/220)',
  '15/9': 'Día Internacional de la Democracia (A/RES/62/7)',
  '16/9': 'Día Internacional de la Ciencia, la Tecnología y la Innovación para el Sur (A/RES/78/259), Día International de la Cardiología Intervencionista (A/76/L.77), y Día Internacional de la Preservación de la Capa de Ozono (A/RES/49/114)',
  '17/9': 'Día Mundial de la Seguridad del Paciente',
  '18/9': 'Día Internacional de la Igualdad Salarial (A/RES/74/142)',
  '20/9': 'Día Mundial de la Limpieza (A/RES/78/122)',
  '21/9': 'Día Internacional de la Paz (A/RES/36/67)',
  '23/9': 'Día Internacional de las Lenguas de Señas (A/RES/72/161)',
  '26/9': 'Día Marítimo Mundial y Día Internacional para la Eliminación Total de las Armas Nucleares (A/RES/68/32)',
  '27/9': 'Día Mundial del Turismo',
  '28/9': 'Día Internacional del Derecho de Acceso Universal a la Información (A/RES/74/5) y Día Mundial contra la Rabia',
  '29/9': 'Día Internacional de Concienciación sobre la Pérdida y el Desperdicio de Alimentos (A/RES/74/209)',
  '30/9': 'Día Internacional de la Traducción (A/RES/71/288)',
  '1/10': 'Día Internacional de las Personas de Edad (A/RES/45/106)',
  '2/10': 'Día Internacional de la No Violencia (A/RES/61/271)',
  '4/10': 'Semana Mundial del Espacio (A/RES/54/68)',
  '5/10': 'Día Mundial de los Docentes (UNESCO) (UNESCO 27 C/INF.7)',
  '7/10': 'Día Mundial del Hábitat (A/RES/40/202 A) y Día Mundial del Algodón (A/RES/75/318)',
  '9/10': 'Día Mundial del Correo (UPU/1969/Res.C.11)',
  '10/10': 'Día Mundial de la Salud Mental (OMS)',
  '11/10': 'Día Mundial de las Aves Migratorias (PNUMA) y Día Internacional de la Niña (A/RES/66/170)',
  '13/10': 'Día Internacional para la Reducción de los Desastres (A/RES/64/200)',
  '15/10': 'Día Internacional de las Mujeres Rurales (A/RES/62/136)',
  '16/10': 'Día Mundial de la Alimentación (A/RES/35/70)',
  '17/10': 'Día Internacional para la Erradicación de la Pobreza (A/RES/47/196)',
  '20/10': 'Día Mundial de la Estadística',
  '23/10': 'Día Internacional del Leopardo de las Nieves (A/RES/79/143)',
  '24/10': 'Semana del Desarme (A/RES/S-10/2 (p. 102)), Semana Mundial de la Alfabetización Mediática e Informacional (A/RES/75/267), Día de las Naciones Unidas (A/RES/168 (II)), y Día Mundial de Información sobre el Desarrollo (A/RES/3038 (XXVII))',
  '27/10': 'Día Mundial del Patrimonio Audiovisual (UNESCO 33/C/Resolution 5)',
  '29/10': 'Día Internacional de los Cuidados y el Apoyo (A/RES/77/317)',
  '31/10': 'Día Mundial de las Ciudades (A/RES/68/239)',
  '2/11': 'Día Internacional para Poner Fin a la Impunidad de los Crímenes contra Periodistas (A/RES/68/163)',
  '5/11': 'Día Mundial de Concienciación sobre los Sunamis (A/RES/70/203)',
  '6/11': 'Día Internacional para la Prevención de la Explotación del Medio Ambiente en la Guerra y los Conflictos Armados (A/RES/56/4)',
  '9/11': 'Semana Internacional de la Ciencia y la Paz (A/RES/43/61)',
  '10/11': 'Día Mundial de la Ciencia para la Paz y el Desarrollo (UNESCO 31 C/Resolution 20)',
  '14/11': 'Día Mundial de la Diabetes (A/RES/61/225)',
  '16/11': 'Día Internacional de la Tolerancia (UNESCO 28 C/Resolution 5.61)',
  '17/11': 'Día mundial en recuerdo de las víctimas de los accidentes de tráfico (A/RES/60/5)',
  '18/11': 'Día Mundial para Prevenir la Explotación, los Abusos y la Violencia Sexuales contra los Niños y Promover la Sanación (A/RES/77/8) y Semana Mundial de Concientización sobre el Uso de los Antimicrobianos, 13-19 noviembre (OMS)',
  '19/11': 'Día Mundial del Retrete (A/RES/67/291)',
  '20/11': 'Día de la Industrialización de África (A/RES/44/237) y Día Mundial de la Infancia (A/RES/836(IX))',
  '21/11': 'Día Mundial de la Filosofía (UNESCO 33 C/Resolution 37) y Día Mundial de la Televisión (A/RES/51/205)',
  '24/11': 'Día Mundial de los Gemelos Unidos (A/RES/78/313)',
  '25/11': 'Día Internacional de la Eliminación de la Violencia contra la Mujer (A/RES/54/134)',
  '26/11': 'Día Mundial del Transporte Sostenible (A/RES/77/286)',
  '29/11': 'Día Internacional de Solidaridad con el Pueblo Palestino (A/RES/32/40B)',
  '30/11': 'Día de Conmemoración de todas las víctimas de la guerra química (OPCW C-20/DEC.10)',
  '1/12': 'Día Mundial del SIDA',
  '2/12': 'Día Internacional para la Abolición de la Esclavitud (A/RES/317(IV))',
  '3/12': 'Día Internacional de las Personas con Discapacidad (A/RES/47/3)',
  '4/12': 'Día Internacional de los Bancos (A/RES/74/245)',
  '5/12': 'Día Mundial del Suelo (A/RES/68/232) y Día Internacional de los Voluntarios (A/RES/40/212)',
  '7/12': 'Día de la Aviación Civil Internacional (A/RES/51/33)',
  '9/12': 'Día Internacional para la Conmemoración y Dignificación de las Víctimas del Crimen de Genocidio y para la Prevención de ese Crimen (A/RES/69/323) y Día Internacional contra la Corrupción (A/RES/58/4)',
  '10/12': 'Día de los Derechos Humanos (A/RES/423 (V))',
  '11/12': 'Día Internacional de las Montañas (A/RES/57/245)',
  '12/12': 'Día Internacional de la Neutralidad (A/RES/71/275) y Día Internacional de la Cobertura Sanitaria Universal (A/RES/72/138)',
  '18/12': 'Día de la lengua árabe y Día Internacional del Migrante (A/RES/55/93)',
  '20/12': 'Día Internacional de la Solidaridad Humana (A/RES/60/209)',
  '21/12': 'Día Mundial de la Meditación (A/RES/79/137) y Día Mundial del Baloncesto (A/RES/77/324)',
};

  ngOnInit(): void {
    this.userName = localStorage.getItem('userName') || '';
    const now = new Date();
    const hour = now.getHours();
    this.greeting = hour < 12 ? 'Buenos días' : hour < 20 ? 'Buenas tardes' : 'Buenas noches';

    this.dailyQuote = this.quotes[Math.floor(Math.random() * this.quotes.length)];
    this.todayDate = now.toLocaleDateString('es-ES', { weekday: 'long', day: 'numeric', month: 'long' });

    const key = `${now.getDate()}/${now.getMonth()+1}`;

    this.efemeride = this.efemerides[key] || 'Hoy no es un día internacional, pero puede ser un gran día para tí.';
  }

  setMood(emoji: string): void {
    this.mood = emoji;
  }
}